### ISSUE TITLE
Get node-sass error on compile

### ISSUE THREAD

**Issue by mrThirsty** [themesberg/volt-react-dashboard#14]
When attempting to run the project (npm start), I get the following error:

./src/scss/volt.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/scss/volt.scss)
Error: Node Sass version 6.0.1 is incompatible with ^4.0.0.

When attempting to install v4.0.0.0 of node-sass I get the below error and can only install the latest version:

2141 warn @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.
2142 warn @babel/plugin-proposal-class-static-block@7.14.5 requires a peer of @babel/core@^7.12.0 but none is installed. You must install peer dependencies yourself.
2143 warn react-chartist@0.14.4 requires a peer of chartist@^0.10.1 but none is installed. You must install peer dependencies yourself.
2144 warn tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
2145 verbose stack Error: node-sass@4.0.0 postinstall: `node scripts/build.js`
2145 verbose stack Exit status 1
2145 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2145 verbose stack     at EventEmitter.emit (node:events:390:28)
2145 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2145 verbose stack     at ChildProcess.emit (node:events:390:28)
2145 verbose stack     at maybeClose (node:internal/child_process:1064:16)
2145 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2146 verbose pkgid node-sass@4.0.0
2147 verbose cwd /Users/andrew/Sandbox/Test/football-client
2148 verbose Darwin 20.6.0
2149 verbose argv "/usr/local/Cellar/node/16.10.0/bin/node" "/usr/local/bin/npm" "install" "node-sass@4.0.0"
2150 verbose node v16.10.0
2151 verbose npm  v6.14.11
2152 error code ELIFECYCLE
2153 error errno 1
2154 error node-sass@4.0.0 postinstall: `node scripts/build.js`
2154 error Exit status 1
2155 error Failed at the node-sass@4.0.0 postinstall script.
2155 error This is probably not a problem with npm. There is likely additional logging output above.
2156 verbose exit [ 1, true ]

**Comment by mdzidic** [comment]
You must downgrade to Node v14.x

Also, check https://www.npmjs.com/package/node-sass

**Comment by mrThirsty** [comment]
Thanks, that got it working.
