### ISSUE TITLE
Use Node v14.19.0!!

### ISSUE THREAD

**Issue by joeychrys** [themesberg/volt-react-dashboard#16]
Because node-gyp v3.8.0 is a dependency, you have to use Node.js 14. The LTS for node v14 is v14.19.0. I love this project and I hope this solves any issues. Cheers!

**Comment by miguel-martinr** [comment]
Hey there! Why has this been closed without adding it to the project's README? 

I've been struggling with errors for almost 2 hours and this fixed it, thank you so much!
