### ISSUE TITLE
Popup advert issue with themeseberg

### ISSUE THREAD

**Issue by RileyManda** [themesberg/volt-react-dashboard#5]
There is a Glassmorphism popup that constantly pops up.How do i get rid of that?
<img width="729" alt="popup" src="https://user-images.githubusercontent.com/37291194/112709921-83018000-8e7a-11eb-8ef5-44e4e61a2023.png">

**Comment by zoltanszogyenyi** [comment]
Hello @RileyManda,

We have disabled it since a few days ago. Feel free to remove the GTM (Google Tag Manager) script to prevent these in the future.

Cheers,
Zoltan
