### ISSUE TITLE
Node modules not installing

### ISSUE THREAD

**Issue by arghanath007** [themesberg/volt-react-dashboard#8]
I am doing yarn in the root directory but it is not installing and it is giving this error ->  An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/5.15.3/fontawesome-free-5.15.3.tgz: Request failed \"401 Unauthorized\""

**Comment by LagunaElectric** [comment]
Same here.

**Comment by cordosvictor** [comment]
Hey @arghanath007 @LagunaElectric 

There was a bug in the reactivation section of the new subscription that didn't properly re-activate the existing NPM token for that particular repository. So please give it a re-try after you had `node_modules` and `yarn.lock`/`package-lock.json` removed.

We will also make an update to our repository as soon as possible.

Sorry for the inconvenience,
Victor

**Comment by LagunaElectric** [comment]
Thanks Victor!

**Comment by arghanath007** [comment]
Thank you. I will it and let you know if it works now.
